services:
  - type: web
    name: resistor-and-gate-calculator
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11.8
